#!/usr/bin/python

import sys
import os

if os.name == 'nt':
    sp = os.path.join(os.path.split(os.path.dirname(__file__))[0],'Lib','site-packages')
    if sp not in sys.path:
        sys.path.append(sp)

import ember.gui

if __name__ == '__main__':
    ember.gui.main()
